site_name: Meu gov.br
theme:
    name: material
    favicon: Images/logo.png
    logo: Images/logo.png
    language: pt
    features:
        - navigation.tabs
        - header.autohide

extra:
    generator: false

hide:
    - toc

nav:
    - Home: index.md
    - Apresentações:
          - Apresentação 01: 'Apresentacao/apresentacao1.md'
          - Apresentacao 02: 'Apresentacao/apresentacao2.md'
          #  - Apresentacao 03: ''
          #  - Apresentacao 04: ''
          #  - Apresentacao 05: ''
          #  - Apresentacao 06: ''
    - Planejamento: 'Planejamento/Planejamento.md'
    - Pré-rastreabilidade: 'Pre-Rastreabilidade/Rich_Picture.md'
    - Elicitação:
          - Personas: 'Elicitacao/Personas.md'
          - Introspecção: 'Elicitacao/introspeccao.md'
          - Questionário: 'Elicitacao/questionario.md'
          - Storyboard: 'Elicitacao/storyboard.md'
          - Priorização:
                - First Things First: 'Elicitacao/Priorizacao/ftf.md'
                - MoSCoW: 'Elicitacao/Priorizacao/moscow.md'
    - Modelagem de Requisitos:
          - Especificação Suplementar: 'Modelagem_Requisitos/EspecificacaoSuplementar.md'
          - Casos de Uso: 'Modelagem_Requisitos/Casos_uso.md'
          - Cenários: 'Modelagem_Requisitos/Cenarios.md'
          - Léxicos: 'Modelagem_Requisitos/Léxicos.md'
    - Análise de Requisitos: 'Analise_Requisitos/'
docs_dir: docs/
